version: '3.8'
services:
  api:
    build: ./api
    tty: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./api/app
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules

  db:
    build: ./db
    tty: true
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./tmp/db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  node_modules: null